import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

const kPrimaryColor = Color(0xff00aeef);
const kGray1 = Color(0xff444F60);
const double kPadding = 16;
const kErrorColor = Color(0xffEF4444);

TextTheme kLightTextTheme = TextTheme(
  headline1: GoogleFonts.poppins(
      fontWeight: FontWeight.w300,
      letterSpacing: 0.15,
      fontSize: 79,
      color: kGray1),
  headline2: GoogleFonts.poppins(
      fontWeight: FontWeight.w300,
      fontSize: 49,
      letterSpacing: -0.15,
      color: kGray1),
  headline3: GoogleFonts.poppins(
      fontWeight: FontWeight.w300, fontSize: 39, color: kGray1),
  headline4: GoogleFonts.poppins(
      fontSize: 28,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: kGray1),
  headline5: GoogleFonts.poppins(
      fontSize: 20, fontWeight: FontWeight.w400, color: kGray1),
  headline6: GoogleFonts.poppins(
      fontSize: 16,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.15,
      color: kGray1),
  subtitle1: GoogleFonts.poppins(
      fontSize: 13,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.15,
      color: kGray1),
  subtitle2: GoogleFonts.poppins(
      fontSize: 11,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.1,
      color: kGray1),
  bodyText1: GoogleFonts.poppins(
      fontSize: 16,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      color: kGray1),
  bodyText2: GoogleFonts.poppins(
      fontSize: 14,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: kGray1),
  button: GoogleFonts.poppins(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      letterSpacing: 1.25,
      color: Colors.white),
  caption: GoogleFonts.poppins(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      color: kGray1),
  overline: GoogleFonts.poppins(
    fontSize: 8,
    fontWeight: FontWeight.w400,
    letterSpacing: 1.5,
    color: kGray1,
  ),
);

List<String> cities = [
  "Adama",
  "Addis Ababa",
  "Addis Alem",
  "Addis Zemen",
  "Adigrat",
  "Adwa",
  "Agaro",
  "Akaki",
  "Alaba ",
  "Alitena",
  "Amba Mariam",
  "Ambo",
  "Ankober",
  "Arba Minch",
  "Arboye",
  "Asaita",
  "Asella",
  "Asosa",
  "Awasa",
  "Awash",
  "Axum",
  "Alamata",
  "Babille",
  "Baco",
  "Badme",
  "Bahir Dar",
  "Bati",
  "Bedele",
  "Beica",
  "Bichena",
  "Bonga",
  "Bishoftu",
  "Ciro",
  "Chencha",
  "Dabat",
  "Dangila",
  "Debark",
  "Debre Berhan",
  "Debre Marqos",
  "Debre Tabor",
  "Debre Werq",
  "Debre Zebit",
  "Dejen",
  "Dembidolo",
  "Dessie",
  "Dila",
  "Dire Dawa",
  "Dolo Bay",
  "Dolo Odo",
  "Durame",
  "Finicha'a",
  "Fiche",
  "Finote Selam",
  "Gambela",
  "Gelemso",
  "Ghimbi",
  "Ginir",
  "Goba",
  "Gode",
  "Gondar",
  "Gongoma",
  "Gore",
  "Gorgora",
  "Guion",
  "Harar",
  "Hayq",
  "Holeta",
  "Hossana",
  "Humera",
  "Imi",
  "Irgalem",
  "Jijiga",
  "Jimma",
  "Jinka",
  "Kabri Dar",
  "Kebri Mangest",
  "Kombolcha",
  "Konso",
  "Kulubi",
  "Kake",
  "Lalibela",
  "Limmu Genet",
  "Maji",
  "Maychew",
  "Mek'ele",
  "Mendi",
  "Metemma",
  "Metu",
  "Mizan Teferi",
  "Mojo",
  "Mota",
  "Moyale",
  "Negash",
  "Negele Boran",
  "Nekemte",
  "Shashamane",
  "Shire",
  "Shilavo",
  "Shonne",
  "Sodore",
  "Tiya",
  "Tippi",
  "Tullu Milki",
  "Turmi",
  "Wacca",
  "Walwal",
  "Werder",
  "Wereta",
  "Woldia",
  "Wolaita sodo",
  "Wolleka",
  "Wuchale",
  "Yabelo",
  "Yeha",
  "Ziway"
];

List<String> nationality = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Ni-Vanuatu",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean"
];
